apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-app-config
  namespace: staging
data:
  SPRING_PROFILES_ACTIVE: "staging"
  SERVER_PORT: "8091"
  SPRING_DATA_REDIS_HOST: "redis.staging.svc"
  SPRING_DATA_REDIS_PORT: "6379"
  MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: "http://zipkin.staging.svc:9411/api/v2/spans"
  MANAGEMENT_ZIPKIN_ENDPOINT: "http://zipkin.staging.svc:9411/api/v2/spans"
  SPRING_ZIPKIN_ENDPOINT: "http://zipkin.staging.svc:9411/api/v2/spans"
  SPRING_ZIPKIN_BASE_URL: "http://zipkin.staging.svc:9411"
  LOGGING_LEVEL_COM_EXAMPLE: "INFO"
  JAVA_OPTS: "-Xms256m -Xmx512m -XX:+UseG1GC -XX:+ExitOnOutOfMemoryError -Duser.timezone=Asia/Taipei -Dmanagement.zipkin.tracing.endpoint=http://zipkin.staging.svc:9411/api/v2/spans -Dmanagement.zipkin.endpoint=http://zipkin.staging.svc:9411/api/v2/spans -Dspring.zipkin.endpoint=http://zipkin.staging.svc:9411/api/v2/spans"
