apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: demo-app-secret
  namespace: prod
  labels:
    app: demo-app
    app.kubernetes.io/name: demo-app
    env: prod
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: demo-app-secret
    creationPolicy: Owner
  data:
    - secretKey: SPRING_DATA_REDIS_PASSWORD
      remoteRef:
        key: secret/redis
        property: password
