apiVersion: v1
kind: Service
metadata:
  name: demo-app
  namespace: prod
  labels:
    app: demo-app
    app.kubernetes.io/name: demo-app
    env: prod
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: demo-app
