apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-app-config
  namespace: dev
data:
  SPRING_PROFILES_ACTIVE: "dev"
  SERVER_PORT: "8090"
  SPRING_DATA_REDIS_HOST: "redis.default.svc"
  SPRING_DATA_REDIS_PORT: "6379"
  MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: "http://zipkin.default.svc:9411/api/v2/spans"
  MANAGEMENT_TRACING_EXPORT_ZIPKIN_ENDPOINT: "http://zipkin.default.svc:9411/api/v2/spans"
  LOGGING_LEVEL_COM_EXAMPLE: "DEBUG"
  JAVA_OPTS: "-XX:MaxRAMPercentage=75.0 -XX:InitialRAMPercentage=50.0 -XX:+UseG1GC -XX:+ExitOnOutOfMemoryError -Duser.timezone=Asia/Taipei -Dmanagement.zipkin.tracing.endpoint=http://zipkin.default.svc:9411/api/v2/spans"
  LOVIUS_VALUE: "123123"