apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
- deployment.yaml
- service.yaml
- configmap.yaml
- external-secret.yaml
- ingress.yaml

images:
- name: ghcr.io/lovius215/demo01
  newName: ghcr.io/lovius215/demo01
  newTag: dev-671f1aa445d9b191fe3b552199229986b8ff7421
