apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
- deployment.yaml
- service.yaml
- configmap.yaml
- external-secret.yaml
- ingress.yaml

images:
- name: ghcr.io/lovius215/demo01
  newName: ghcr.io/lovius215/demo01
  newTag: dev-a880f011d8da25052d5dc2b044f1c75d0de663f4
