apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
- deployment.yaml
- service.yaml
- configmap.yaml
- external-secret.yaml
- ingress.yaml

images:
- name: ghcr.io/lovius215/demo01
  newName: ghcr.io/lovius215/demo01
  newTag: dev-df5cd69ca132c509b31c0c34bbb862bd6e440173
