apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - ../../base
  - configmap.yaml
  - external-secret.yaml

patches:
  - path: deployment-patch.yaml

images:
  - name: ghcr.io/lovius215/demo01
    newTag: dev-latest
